### ISSUE TITLE
Add Dijkstra Algorithm

### ISSUE THREAD

**Issue by imrahul361** [imrahul361/Competitive-Programming-Libraries#8]
Create a function for Dijkstra's Algorithm with Detailed Comments.

**Comment by codewdhruv** [comment]
I would like to contribute to this in C++
Kindly assign me @imrahul361

**Comment by imrahul361** [comment]
Ok Take it

**Comment by imrahul361** [comment]
Take any one issue for now.
Let others to contribute for the same @dhrubajyoti89

**Comment by rashipathak** [comment]
May I take this @imrahul361 ?

**Comment by imrahul361** [comment]
ok take it @rashipathak

**Comment by rashipathak** [comment]
thanks!
